// Generated by `npm run catalogue` — do not edit by hand; edit holdings.json.
// 14 volumes with 5 holders; 4 digitised, 1010 Gallica views. Manifests read 2026-09-10.

import type { ArchiveGroup, Holder, Volume } from '../lib/types.ts';

export const HOLDERS: Holder[] = [
  {
    "id": "bnf",
    "name": "Bibliothèque nationale de France, département des Manuscrits",
    "short": "BnF",
    "city": "Paris",
    "url": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc54223p",
    "access": "iiif",
    "terms": "Gallica's conditions: non-commercial reuse of public-domain digitisations is free, provided the source is stated as « Source gallica.bnf.fr / Bibliothèque nationale de France »; commercial reuse needs a licence. The IIIF manifests and images are served with Access-Control-Allow-Origin: * (measured 10 September 2026), so a browser may read them directly from this site.",
    "termsUrl": "https://gallica.bnf.fr/html/und/conditions-dutilisation-des-contenus-de-gallica"
  },
  {
    "id": "academie",
    "name": "Archives de l'Académie des sciences (Institut de France)",
    "short": "Académie",
    "city": "Paris",
    "url": "https://archives.academie-sciences.fr/",
    "access": "onsite",
    "terms": "The three prize memoirs are not digitised. The Archives' portal is consulted on site or by appointment; the two extracts reproduced by France Mémoire in 2023 are credited « © Archives de l'Académie des sciences », so the Académie asserts rights on its reproductions and nothing of them is shown here.",
    "termsUrl": "https://archives.academie-sciences.fr/n/naviguer-sur-le-portail/n:148"
  },
  {
    "id": "moreniana",
    "name": "Biblioteca Moreniana, Nuovo Fondo Libri and Fondo Palagi-Libri",
    "short": "Moreniana",
    "city": "Florence",
    "url": "http://dm.unife.it/geometria/storia/Germain_en.html",
    "access": "onsite",
    "terms": "Not digitised, to our knowledge. Known through Andrea Del Centina's editions (2005, 2008), which are his and are linked, not copied.",
    "termsUrl": "https://link.springer.com/article/10.1007/s00407-007-0016-4"
  },
  {
    "id": "goettingen",
    "name": "Niedersächsische Staats- und Universitätsbibliothek, Gauß-Nachlass",
    "short": "Göttingen",
    "city": "Göttingen",
    "url": "https://gauss.adw-goe.de/",
    "access": "database",
    "terms": "The Gauß-Briefdatenbank of the Göttingen Academy lists every letter to and from Gauss and links scans or transcriptions for most. Its terms have not been verified by this site, which links to it and embeds nothing.",
    "termsUrl": "https://gauss.adw-goe.de/"
  },
  {
    "id": "nypl",
    "name": "New York Public Library, Manuscripts and Archives Division",
    "short": "NYPL",
    "city": "New York",
    "url": "https://www.nypl.org/research/research-catalog",
    "access": "onsite",
    "terms": "One undated letter to Legendre, cited by Laubenbacher and Pengelley. Not known to be online.",
    "termsUrl": null
  }
];

export const GROUPS: ArchiveGroup[] = [
  {
    "id": "papiers",
    "title": "Papiers de Sophie Germain — Français 9114-9117",
    "date": "XIXe siècle",
    "cotes": [
      "fr-9114",
      "fr-9115",
      "fr-9116",
      "fr-9117"
    ]
  },
  {
    "id": "correspondance",
    "title": "Correspondance — Français 9118, NAF 4073 and 5166",
    "date": "1801-1831",
    "cotes": [
      "fr-9118",
      "naf-4073",
      "naf-5166"
    ]
  },
  {
    "id": "academie",
    "title": "The three prize memoirs — Archives de l'Académie des sciences",
    "date": "1811-1815",
    "cotes": [
      "ads-1811",
      "ads-1813",
      "ads-1815"
    ]
  },
  {
    "id": "florence",
    "title": "What Libri kept — Biblioteca Moreniana, Florence",
    "date": "",
    "cotes": [
      "moreniana-nfl",
      "moreniana-palagi"
    ]
  },
  {
    "id": "goettingen",
    "title": "Her letters to Gauss — Göttingen",
    "date": "1804-1819",
    "cotes": [
      "sub-gauss"
    ]
  },
  {
    "id": "nypl",
    "title": "One letter to Legendre — New York",
    "date": "s.d.",
    "cotes": [
      "nypl-legendre"
    ]
  }
];

export const COTES: Volume[] = [
  {
    "id": "fr-9114",
    "holder": "bnf",
    "shelfmark": "Français 9114",
    "title": "Papiers de Sophie GERMAIN. — Recueil de dissertations et problèmes mathématiques et physiques.",
    "date": "XIXe siècle",
    "folios": 362,
    "extent": "Papier. 362 feuillets. 390 × 230 mm. Demi-reliure. Ancienne cote : Supplément français 2273, a.",
    "notice": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc54223p",
    "ark": null,
    "note": "The first of the three volumes of « Papiers », and the one holding her two principal Fermat manuscripts — the polished « Remarques sur l'impossibilité… » (ff. 198r–208v) and the « Démonstration… z^{2(8n±3)} » (ff. 92r–94v) — as located by Laubenbacher and Pengelley. Not digitised: the BnF catalogue marks only 9115 as « consultable sur Gallica ». A microfilm exists (MF 32863, by inference from its neighbours; not verified).",
    "pages": 0,
    "group": "papiers"
  },
  {
    "id": "fr-9115",
    "holder": "bnf",
    "shelfmark": "Français 9115",
    "title": "Papiers de Sophie GERMAIN. — Recueil de dissertations et problèmes mathématiques et physiques.",
    "date": "1801-1900",
    "folios": 372,
    "extent": "Papier. 372 feuillets. 390 × 230 mm. Demi-reliure. Ancienne cote : Supplément français 2273, a-b.",
    "notice": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc54223p/ca59902191713965",
    "ark": "btv1b90724875",
    "note": "The one digitised volume of the « Papiers », from the original (a second digitisation, from the microfilm MF 32864, is ark btv1b52520081q). Number theory and physics side by side, unnumbered except by the archive. Laubenbacher and Pengelley locate « Manuscript C » — three polished pages claiming Fermat for all even exponents — at ff. 348r–349r.",
    "pages": 750,
    "group": "papiers"
  },
  {
    "id": "fr-9116",
    "holder": "bnf",
    "shelfmark": "Français 9116",
    "title": "Papiers de Sophie GERMAIN. — Recueil de dissertations et problèmes mathématiques et physiques.",
    "date": "XIXe siècle",
    "folios": 211,
    "extent": "Papier. 211 feuillets. 390 × 230 mm. Demi-reliure. Ancienne cote : Supplément français 2273, b.",
    "notice": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc54223p",
    "ark": null,
    "note": "The third volume of the « Papiers ». Not digitised. Bucciarelli and Dworsky drew on these volumes for the elasticity work; which leaves are physics and which are number theory has not been published leaf by leaf.",
    "pages": 0,
    "group": "papiers"
  },
  {
    "id": "fr-9117",
    "holder": "bnf",
    "shelfmark": "Français 9117",
    "title": "« Considérations générales sur l'état des sciences et des lettres aux différentes époques de leur culture, » par Sophie GERMAIN.",
    "date": "1801-1900",
    "folios": 54,
    "extent": "Papier. 54 feuillets. 380 × 210 mm. Demi-reliure.",
    "notice": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc54224x",
    "ark": "btv1b90075733",
    "note": "The philosophical essay, published posthumously by her nephew Lherbette in 1833 and again by Stupuy in 1879. Digitised from the microfilm. Not mathematics, and already in print: listed for completeness and marked as edited.",
    "pages": 113,
    "group": "papiers"
  },
  {
    "id": "fr-9118",
    "holder": "bnf",
    "shelfmark": "Français 9118",
    "title": "Correspondance de Sophie GERMAIN avec les mathématiciens et savants Cauchy, Delambre, Fourier, Gauss, Le Gendre, d'Ansse de Villoison, etc.",
    "date": "1801-1900",
    "folios": 93,
    "extent": "Papier. 93 feuillets. 270 × 160 mm. Demi-reliure.",
    "notice": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc542255",
    "ark": "btv1b9007572p",
    "note": "Letters received, for the most part: Gauss's to her, Legendre's, Cauchy's, Fourier's. Digitised from the microfilm, so in black and white. The Gauss letters are edited in Del Centina and Fiocca (2012).",
    "pages": 103,
    "group": "correspondance"
  },
  {
    "id": "naf-4073",
    "holder": "bnf",
    "shelfmark": "NAF 4073",
    "title": "Correspondance de Sophie GERMAIN.",
    "date": "XVIIIe siècle",
    "folios": 32,
    "extent": "Papier. 32 feuillets. Montés in-4°. Demi-reliure.",
    "notice": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc40103f",
    "ark": "btv1b10089787b",
    "note": "« Lettres de Delambre, Joseph Fourier, Sophie Germain, Lagrange, Lalande et G. Libri. Provient des papiers de Libri. » The catalogue's « XVIIIe siècle » is its own; several letters are plainly later. Also on Europeana Transcribe, where volunteers have begun a transcription under a public-domain rights statement.",
    "pages": 44,
    "group": "correspondance"
  },
  {
    "id": "naf-5166",
    "holder": "bnf",
    "shelfmark": "NAF 5166",
    "title": "[Papiers de Libri : pièces concernant Sophie Germain]",
    "date": "",
    "folios": null,
    "extent": "",
    "notice": "https://archivesetmanuscrits.bnf.fr/ark:/12148/cc40103f",
    "ark": null,
    "note": "Named only by the cross-reference in the NAF 4073 notice — « Cf. les mss. français 9114-9118, NAF 4073 et 5166 ». Its own notice has not been read and its contents are not known to this site; the bracketed title is ours. Listed so that nobody assumes the BnF's Germain holdings end at 9118.",
    "pages": 0,
    "group": "correspondance"
  },
  {
    "id": "ads-1811",
    "holder": "academie",
    "shelfmark": "Archives des prix, 1811",
    "title": "Mémoire sur cette question proposée par la première classe de l'Institut : « Donner la théorie mathématique des vibrations des surfaces élastiques et la comparer à l'expérience » — premier mémoire, 21 septembre 1811",
    "date": "21 septembre 1811",
    "folios": null,
    "extent": "Devise : « Effectuum naturalium ejusdem generis eædem sunt causæ ».",
    "notice": "https://archives.academie-sciences.fr/",
    "ark": null,
    "note": "The first memoir, the only entry to the prize of 1811, not awarded. Its sixth-order equation of motion was wrong and the commission said so. Consultable at the Archives des prix, Bibliothèque de l'Institut; transcribed in Annexe D of Grun (2022), whose text is hers. Not digitised.",
    "pages": 0,
    "group": "academie"
  },
  {
    "id": "ads-1813",
    "holder": "academie",
    "shelfmark": "Archives des prix, 1813",
    "title": "Mémoire sur cette question proposée par la première classe de l'Institut — second mémoire, septembre 1813",
    "date": "septembre 1813",
    "folios": null,
    "extent": "",
    "notice": "https://archives.academie-sciences.fr/",
    "ark": null,
    "note": "The second memoir, awarded an honourable mention: the fourth-order equation the commission recognised as correct, with her own comparison against Chladni's figures. It carries the only drawings in her hand that survive. Transcribed in Grun (2022), Annexe D. Not digitised.",
    "pages": 0,
    "group": "academie"
  },
  {
    "id": "ads-1815",
    "holder": "academie",
    "shelfmark": "Archives des prix, 1815",
    "title": "Mémoire sur cette question proposée par la première classe de l'Institut — troisième mémoire, septembre 1815",
    "date": "septembre 1815",
    "folios": null,
    "extent": "",
    "notice": "https://archives.academie-sciences.fr/",
    "ark": null,
    "note": "The third memoir, awarded the prix extraordinaire on 8 January 1816. Reworked and printed by her in 1821 as « Recherches sur la théorie des surfaces élastiques », which is in the public domain and on Gallica; the manuscript itself is transcribed in Grun (2022), Annexe D. Not digitised.",
    "pages": 0,
    "group": "academie"
  },
  {
    "id": "moreniana-nfl",
    "holder": "moreniana",
    "shelfmark": "Nuovo Fondo Libri, cass. 11 (and others)",
    "title": "[Manuscrits scientifiques de Sophie Germain : travaux, comptes rendus d'expériences, brouillons de lettres à Gauss, Legendre et Lagrange, remarques sur Cauchy et Navier]",
    "date": "",
    "folios": null,
    "extent": "« More than two hundred sheets » (Del Centina).",
    "notice": "http://dm.unife.it/geometria/storia/Germain_en.html",
    "ark": null,
    "note": "What Libri still had in 1868. Among it the 24-page « Remarques sur l'impossibilité de satisfaire à l'équation x^p + y^p = z^p » (cass. 11, ins. 266), the draft of which the BnF's Français 9114 holds the fair copy, transcribed by Del Centina (2008). The bracketed title is ours, from his description. Not digitised.",
    "pages": 0,
    "group": "florence"
  },
  {
    "id": "moreniana-palagi",
    "holder": "moreniana",
    "shelfmark": "Fondo Palagi-Libri",
    "title": "[Lettres de Sophie Germain à Guglielmo Libri, et brouillons à Poinsot, Legendre et Lagrange]",
    "date": "1819-1831",
    "folios": null,
    "extent": "Nine letters, per Del Centina (2005).",
    "notice": "https://www.sciencedirect.com/science/article/pii/S0315086003001022",
    "ark": null,
    "note": "Published whole by Del Centina in Historia Mathematica 32 (2005). The bracketed title is ours. Not digitised.",
    "pages": 0,
    "group": "florence"
  },
  {
    "id": "sub-gauss",
    "holder": "goettingen",
    "shelfmark": "Gauß-Nachlass, Briefe A : Germain",
    "title": "[Lettres de Sophie Germain à Carl Friedrich Gauss, 1804-1819, avec leurs annexes mathématiques]",
    "date": "1804-1819",
    "folios": null,
    "extent": "Ten letters and their enclosures, per Del Centina and Fiocca (2012); the letter of 12 May 1819 runs to eight numbered sheets.",
    "notice": "https://gauss.adw-goe.de/",
    "ark": null,
    "note": "Her side of the correspondence, first published in part by Boncompagni in 1880 (« Cinq lettres », public domain, on Gallica) and edited whole with the mathematical enclosures by Del Centina and Fiocca (2012). The bracketed title is ours. The Göttingen letter database may hold scans; this site has not verified on what terms and links rather than embeds.",
    "pages": 0,
    "group": "goettingen"
  },
  {
    "id": "nypl-legendre",
    "holder": "nypl",
    "shelfmark": "Manuscripts and Archives Division",
    "title": "[Lettre de Sophie Germain à Legendre sur le théorème de Fermat, sans date]",
    "date": "s.d.",
    "folios": null,
    "extent": "Three pages, per Laubenbacher and Pengelley.",
    "notice": "https://www.nypl.org/research/research-catalog",
    "ark": null,
    "note": "Cited by Laubenbacher and Pengelley (2010) as one of the seven primary pieces of her work on Fermat. The bracketed title is ours. Not known to be online.",
    "pages": 0,
    "group": "nypl"
  }
];

export const BY_ID = new Map(COTES.map((c) => [c.id, c]));
export const HOLDER_BY_ID = new Map(HOLDERS.map((h) => [h.id, h]));
