import { GROUPS, BY_ID } from './catalogue.ts';

/**
 * The timeline: who the nineteen are, in the order of their lives.
 *
 * Dates and the one-paragraph biographies are ours, written short on purpose —
 * a reader who wants more has Wikipedia a click away, and this page's job is to
 * put the volumes in the order of the people who wrote them. What each person
 * has in Gallica is not written here: it is counted from the catalogue, so the
 * page cannot drift from it.
 *
 * Portraits are hotlinked from Wikimedia Commons, as on the sibling
 * duty.commutator.io, and only from files in the public domain or under a
 * licence that permits reuse, credited under the timeline. Claude Mydorge has no
 * portrait on Commons, and his plate shows his initials rather than a likeness
 * nobody made.
 */
export type Portrait = { src: string; page: string; by: string; licence: string };

export interface Life {
  /** The catalogue group id: « fourier ». */
  id: string;
  name: string;
  born: number;
  died: number;
  /** True where the birth year is uncertain. */
  bornApprox?: boolean;
  /** Where, and what they did for a living. */
  role: string;
  bio: string;
  portrait?: Portrait;
}

const LIVES: Life[] = [
  {"id": "maurolico", "name": "Francesco Maurolico", "born": 1494, "died": 1575, "role": "Messina · abbot, mathematician", "bio": "A Benedictine abbot in Messina who restored the Greek mathematicians — Euclid, Archimedes, Apollonius — in Latin editions of his own. His arithmetic of 1575 contains one of the earliest proofs by induction.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Francesco_Maurolico_engraving_by_Marino_Bovi_after_Polidoro_da_Caravaggio.jpg/500px-Francesco_Maurolico_engraving_by_Marino_Bovi_after_Polidoro_da_Caravaggio.jpg", "page": "https://commons.wikimedia.org/wiki/File:Francesco_Maurolico_engraving_by_Marino_Bovi_after_Polidoro_da_Caravaggio.jpg", "by": "Mariano Bovi, engraving", "licence": "CC BY 4.0"}},
  {"id": "viete", "name": "François Viète", "born": 1540, "died": 1603, "role": "Poitou, Paris · lawyer, royal councillor", "bio": "A lawyer and councillor to Henri III and Henri IV, who did his mathematics beside the law and broke Spanish ciphers for the king. His In artem analyticem isagoge (1591) wrote knowns and unknowns alike as letters, the first algebra of symbols.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Francois_Viete.jpg/500px-Francois_Viete.jpg", "page": "https://commons.wikimedia.org/wiki/File:Francois_Viete.jpg", "by": "unknown artist", "licence": "Public domain"}},
  {"id": "mydorge", "name": "Claude Mydorge", "born": 1585, "died": 1647, "role": "Paris · magistrate, geometer", "bio": "A Paris magistrate of private means, friend and supporter of Descartes, who ground lenses and worked on optics. His Prodromi catoptricorum et dioptricorum (1631–1639) is a treatise on the conic sections."},
  {"id": "mersenne", "name": "Marin Mersenne", "born": 1588, "died": 1648, "role": "Paris · Minim friar", "bio": "A Minim friar in Paris through whose letters Descartes, Fermat, Roberval, Pascal, Galileo and Huygens reached one another — the post office of seventeenth-century science. The Harmonie universelle (1636–1637) is his; so is the name of the Mersenne primes.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/MarinMersenneDuflos.jpg/500px-MarinMersenneDuflos.jpg", "page": "https://commons.wikimedia.org/wiki/File:MarinMersenneDuflos.jpg", "by": "Claude Duflos", "licence": "Public domain"}},
  {"id": "descartes", "name": "René Descartes", "born": 1596, "died": 1650, "role": "Touraine, the Dutch Republic, Stockholm · philosopher", "bio": "Philosopher and mathematician who spent most of his working life in the Dutch Republic and died in Stockholm. La Géométrie (1637) joined algebra to geometry and gave coordinates their method.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg/500px-Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg", "page": "https://commons.wikimedia.org/wiki/File:Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg", "by": "after Frans Hals", "licence": "Public domain"}},
  {"id": "fermat", "name": "Pierre de Fermat", "born": 1601, "died": 1665, "bornApprox": true, "role": "Toulouse · councillor at the parlement", "bio": "A magistrate at the parlement of Toulouse who published almost nothing and wrote his mathematics in letters, many through Mersenne. Maxima and minima, the foundations of number theory, probability with Pascal, and the theorem in the margin are his.", "portrait": {"src": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Pierre_de_Fermat.jpg", "page": "https://commons.wikimedia.org/wiki/File:Pierre_de_Fermat.jpg", "by": "unknown artist", "licence": "Public domain"}},
  {"id": "roberval", "name": "Gilles Personne de Roberval", "born": 1602, "died": 1675, "role": "Paris · professor at the Collège royal", "bio": "Held the chair of mathematics at the Collège royal for forty years, keeping his methods to himself to defend it in the triennial contest. He found tangents by composing motions, measured the cycloid, and gave his name to a balance.", "portrait": {"src": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Gilles_personne_de_roberval.jpg", "page": "https://commons.wikimedia.org/wiki/File:Gilles_personne_de_roberval.jpg", "by": "Henri Testelin", "licence": "Public domain"}},
  {"id": "sluse", "name": "René-François de Sluse", "born": 1622, "died": 1685, "role": "Liège · canon", "bio": "A canon of the cathedral of Liège who corresponded with Pascal, Huygens and Oldenburg. His Mesolabum (1659) and his rule for tangents to algebraic curves were widely used before the calculus.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Portret_van_Ren%C3%A9-Fran%C3%A7ois_Walter_de_Sluse_Ren%C3%A9%2C_Fran%C3%A7ois_de_Sluse%2C_chanoine_del%27eglise_cathedrale_de_liege_et_abbe_d%27Amaij_%28titel_op_object%29%2C_RP-P-1906-764.jpg/500px-thumbnail.jpg", "page": "https://commons.wikimedia.org/wiki/File:Portret_van_Ren%C3%A9-Fran%C3%A7ois_Walter_de_Sluse_Ren%C3%A9,_Fran%C3%A7ois_de_Sluse,_chanoine_del%27eglise_cathedrale_de_liege_et_abbe_d%27Amaij_(titel_op_object),_RP-P-1906-764.jpg", "by": "Rijksmuseum", "licence": "CC0"}},
  {"id": "pascal", "name": "Blaise Pascal", "born": 1623, "died": 1662, "role": "Clermont, Paris · mathematician, philosopher", "bio": "Wrote on conic sections at sixteen, built a calculating machine at nineteen, and with Fermat founded the calculus of probabilities in 1654. The arithmetical triangle and the cycloid came before the Pensées, left in fragments at his death.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Blaise_Pascal_Versailles.JPG/500px-Blaise_Pascal_Versailles.JPG", "page": "https://commons.wikimedia.org/wiki/File:Blaise_Pascal_Versailles.JPG", "by": "after François II Quesnel", "licence": "Public domain"}},
  {"id": "lhospital", "name": "Guillaume de L'Hospital", "born": 1661, "died": 1704, "role": "Paris · marquis", "bio": "A marquis and officer who paid Johann Bernoulli for lessons in the new calculus. His Analyse des infiniment petits (1696), the first textbook of differential calculus, carries the rule that bears his name.", "portrait": {"src": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Guillaume_de_l%27H%C3%B4pital.jpg", "page": "https://commons.wikimedia.org/wiki/File:Guillaume_de_l%27H%C3%B4pital.jpg", "by": "unknown artist", "licence": "Public domain"}},
  {"id": "varignon", "name": "Pierre Varignon", "born": 1654, "died": 1722, "role": "Caen, Paris · abbé, professor", "bio": "A priest who taught mathematics at the Collège Mazarin and the Collège royal. His Projet d'une nouvelle mécanique (1687) set out the composition of forces, and he defended Leibniz's calculus at the Académie.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Pierre_Varignon.jpg/500px-Pierre_Varignon.jpg", "page": "https://commons.wikimedia.org/wiki/File:Pierre_Varignon.jpg", "by": "unknown artist", "licence": "Public domain"}},
  {"id": "chatelet", "name": "Émilie du Châtelet", "born": 1706, "died": 1749, "role": "Paris, Cirey · natural philosopher", "bio": "Natural philosopher who brought Leibniz and Newton together in her Institutions de physique (1740). Her French translation of Newton's Principia, with its commentary, finished in the months before her death, is still the standard one.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Emilie_Chatelet_portrait_by_Latour.jpg/500px-Emilie_Chatelet_portrait_by_Latour.jpg", "page": "https://commons.wikimedia.org/wiki/File:Emilie_Chatelet_portrait_by_Latour.jpg", "by": "after Maurice Quentin de La Tour", "licence": "Public domain"}},
  {"id": "dalembert", "name": "Jean Le Rond d'Alembert", "born": 1717, "died": 1783, "role": "Paris · geometer, encyclopédiste", "bio": "Abandoned as a baby on the steps of a Paris church, he became a member of the Académie des sciences at twenty-three. His Traité de dynamique (1743) states his principle, he wrote down the wave equation in 1747, and he co-edited the Encyclopédie with Diderot.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Jean_Le_Rond_d%27Alembert%2C_by_French_school.jpg/500px-Jean_Le_Rond_d%27Alembert%2C_by_French_school.jpg", "page": "https://commons.wikimedia.org/wiki/File:Jean_Le_Rond_d%27Alembert,_by_French_school.jpg", "by": "after Maurice Quentin de La Tour", "licence": "Public domain"}},
  {"id": "lagrange", "name": "Joseph-Louis Lagrange", "born": 1736, "died": 1813, "role": "Turin, Berlin, Paris · geometer", "bio": "Born in Turin, he succeeded Euler in Berlin in 1766 and came to Paris in 1787. The Mécanique analytique (1788) recast mechanics as analysis, without a single figure; the calculus of variations and much of number theory are also his.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Joseph_Louis_Lagrange.jpg/500px-Joseph_Louis_Lagrange.jpg", "page": "https://commons.wikimedia.org/wiki/File:Joseph_Louis_Lagrange.jpg", "by": "unknown artist", "licence": "Public domain"}},
  {"id": "condorcet", "name": "Condorcet", "born": 1743, "died": 1794, "role": "Paris · mathematician, philosopher", "bio": "Perpetual secretary of the Académie des sciences, who applied probability to elections and juries and found the paradox of majority voting. A Girondin under the Terror, he wrote the Esquisse d'un tableau historique des progrès de l'esprit humain in hiding, and died in prison.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Nicolas_de_Condorcet.PNG/500px-Nicolas_de_Condorcet.PNG", "page": "https://commons.wikimedia.org/wiki/File:Nicolas_de_Condorcet.PNG", "by": "unidentified painter", "licence": "Public domain"}},
  {"id": "prony", "name": "Gaspard de Prony", "born": 1755, "died": 1839, "role": "Paris · engineer", "bio": "Engineer and, for forty years, director of the École des ponts et chaussées. For the tables of the cadastre he organised the computing of logarithms as a division of labour among human calculators; the Prony brake and Prony's method are his.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Gaspard_de_Prony.jpg/500px-Gaspard_de_Prony.jpg", "page": "https://commons.wikimedia.org/wiki/File:Gaspard_de_Prony.jpg", "by": "unknown artist", "licence": "Public domain"}},
  {"id": "fourier", "name": "Joseph Fourier", "born": 1768, "died": 1830, "role": "Auxerre, Grenoble, Paris · mathematician, prefect", "bio": "Went to Egypt with Bonaparte, then governed the Isère as prefect while working on heat. The Théorie analytique de la chaleur (1822) gave the heat equation and the trigonometric series that carry his name; he was perpetual secretary of the Académie from 1822.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Fourier2_-_restoration1.jpg/500px-Fourier2_-_restoration1.jpg", "page": "https://commons.wikimedia.org/wiki/File:Fourier2_-_restoration1.jpg", "by": "Julien-Léopold Boilly", "licence": "Public domain"}},
  {"id": "germain", "name": "Sophie Germain", "born": 1776, "died": 1831, "role": "Paris · mathematician", "bio": "Self-taught, she wrote to Lagrange and to Gauss under the name « M. Le Blanc ». She won the Académie's prize on the vibration of elastic surfaces in 1816, and in 1823 Legendre credited her with the theorem on Fermat's Last Theorem that now bears her name.", "portrait": {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Germain_-_%C5%92uvres_philosophiques%2C_1896_%28Illustration_page_4%29.jpg/500px-Germain_-_%C5%92uvres_philosophiques%2C_1896_%28Illustration_page_4%29.jpg", "page": "https://commons.wikimedia.org/wiki/File:Germain_-_%C5%92uvres_philosophiques,_1896_(Illustration_page_4).jpg", "by": "engraving in her Œuvres philosophiques, 1896", "licence": "Public domain"}},
  {"id": "libri", "name": "Guillaume Libri", "born": 1803, "died": 1869, "role": "Florence, Paris, London · mathematician, bibliophile", "bio": "A Florentine mathematician who settled in Paris, entered the Académie in 1833 and wrote the Histoire des sciences mathématiques en Italie. Appointed to inspect France's libraries, he was accused of stealing from them, fled to London in 1848, and was condemned in his absence; much of what he took came back to the BnF.", "portrait": {"src": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Guglielmo_Libri_Carucci_dalla_Sommaja.jpg", "page": "https://commons.wikimedia.org/wiki/File:Guglielmo_Libri_Carucci_dalla_Sommaja.jpg", "by": "Alexis-Nicolas Noël, lithograph", "licence": "Public domain"}},
];

/** In the order of their births. */
export const TIMELINE: Life[] = [...LIVES].sort((a, b) => a.born - b.born);

/** The span the ruler covers. */
export const SPAN = {
  from: Math.min(...LIVES.map((l) => l.born)),
  to: Math.max(...LIVES.map((l) => l.died)),
};

/** What Gallica holds of a life, counted from the catalogue. */
export function holdingsOf(id: string) {
  const g = GROUPS.find((x) => x.id === id);
  const cotes = (g?.cotes ?? []).map((c) => BY_ID.get(c)).filter((v) => v !== undefined);
  return { group: g, volumes: cotes.length, views: cotes.reduce((s, v) => s + v.pages, 0) };
}

export const CREDITS = TIMELINE.flatMap((l) => (l.portrait ? [{ life: l, portrait: l.portrait }] : []));
